### PR TITLE
MSYS2 Mingw64 support + MD5 computation for MSYS2/VS builds

### PR DESCRIPTION
**Pull request by oxillo**
replace PR #123 

-  Build libraries for mingw64
-  ~~Generates MD5SUM for each generated zip file~~
- only deploy if built on openframeworks repo

### CODE REVIEW

**Comment by oxillo** [comment]
Appveyor CI fails because compression do not happen on PR branch (premature exit in build.sh)
Some Travis CI fail because of server time out.

**Comment by arturoc** [comment]
There is a check to not do that on PRs it shouldn't fail but just not try to compress it

**Comment by oxillo** [comment]
Will just remove the MD5 commit for now and work on a better solution

**Comment by arturoc** [comment]
That's perfect thanks! linuxarmv7 is failing to build now but it doesn't seem related so i'm going to merge it

**Pull request merged**
