### PR TITLE
detect osx version and divide 32bit install with 64bit install on osx

### PR DESCRIPTION
**Pull request by kyeshmz**
#138 
Added a `if [ $ARCH == 32 ] ; then` for each formula and also a detect one liner for 64bit compatible os

### CODE REVIEW

**Comment by kkshmz** [comment]
@arturoc 
I see that some formulas such as cairo.sh have 2 build options of building with and without the -mmacosx-version-min= argument.
Is there a reason that we do not default to explicit mmacosx version?

**Comment by arturoc** [comment]
I think this is just because some of these arguments were added at different times by dfifferent people, if you want to make the arguments equal across formulas for osx that would be great

**Comment by kkshmz** [comment]
Hmm, this didnt merge all the commits into one like I wanted it to, but this should work now, if you want to check once the tests complete. @arturoc

**Comment by arturoc** [comment]
The problem with this is that it builds one architecture or the other but not both in a universal library as we had until now. The idea was to keep having universal binaries for a while just in case.

**Comment by kkshmz** [comment]
I see now what you meant by your first comment in the other thread,
I think I will go with something like this 
```
if ["$EXPLICIT_ARCH" == "true"] ; then 
		# these flags are used to create a fat 32/64 binary with i386->libstdc++, x86_64->libc++
		# see https://gist.github.com/tgfrerer/8e2d973ed0cfdd514de6
			if [ "$ARCH" == "32" ] ; then
				local FAT_LDFLAGS="-arch i386 -mmacosx-version-min=${OSX_MIN_SDK_VER}"
			elif [ "$ARCH" == "64" ] ; then
				local FAT_LDFLAGS="-arch x86_64 -mmacosx-version-min=${OSX_MIN_SDK_VER}"
			fi
			./configure LDFLAGS="${FAT_LDFLAGS} " \
				CFLAGS="-O3 ${FAT_LDFLAGS}" \
				--prefix=$BUILD_ROOT_DIR \
				--disable-dependency-tracking \
				--disable-gtk \
				--disable-shared \
                --disable-mmx
			# only build & install lib, ignore demos/tests
			cd pixman
			make clean
			make -j${PARALLEL_MAKE}
		else
		local FAT_LDFLAGS="-arch i386 -mmacosx-version-min=${OSX_MIN_SDK_VER}"
		local FAT_LDFLAGS="-arch x86_64 -mmacosx-version-min=${OSX_MIN_SDK_VER}"
		./configure LDFLAGS="${FAT_LDFLAGS} " \
				CFLAGS="-O3 ${FAT_LDFLAGS}" \
				--prefix=$BUILD_ROOT_DIR \
				--disable-dependency-tracking \
				--disable-gtk \
				--disable-shared \
                --disable-mmx
		# only build & install lib, ignore demos/tests
		cd pixman
		make clean
		make -j${PARALLEL_MAKE}
```

**Comment by arturoc** [comment]
yes that sounds good, if an specific flag is specified then it should build that architecture, otherwise it should build a universal binary as it was doing until now. thanks!

**Pull request closed without merging**
