### PR TITLE
OpenSSL and Poco Updates.

### PR DESCRIPTION
**Pull request by danoli3**
From https://github.com/openframeworks/openFrameworks/pull/4808

Related: https://github.com/openframeworks/apothecary/issues/44

### CODE REVIEW

**Comment by danoli3** [comment]
Yeah I never really understood why we did this:

```
else
git checkout $1/include/openssl/opensslconf_osx.h
git checkout $1/include/openssl/opensslconf_ios.h
git checkout $1/include/openssl/opensslconf_android.h
git checkout $1/include/openssl/opensslconf_vs.h
git checkout $1/include/openssl/opensslconf_win32.h
fi
```
Causing it to break currently.

**Comment by danoli3** [comment]
Okay that should fix some things up... lets see how this goes.

**Comment by arturoc** [comment]
this seems to revert all the fixes i did in this repo. have you taken it from the old repo? 

among other things i moved the poco modules to compile out of each platform so we can have the same for every  platform easily and also simplified a lot the osx build phase to not use lipo and instead just build using "-arch=i386 -arch=x86_64" which produces universal builds right away.

There were also some optimizations to make it faster cause otherwise travis some times failed cause the task took too long

**Comment by danoli3** [comment]
S%I@(#$, yeah I'll fix that

**Comment by danoli3** [comment]
New SourceTree Version fucked up the file too...

**Pull request closed without merging**
