### PR TITLE
updating ofxSvg libs to include linuxaarch64

### PR DESCRIPTION
**Pull request by dimitre**

### CODE REVIEW

**Comment by ofTheo** [comment]
looks like it needs an aarch64 equivalent of this too: 
https://github.com/openframeworks/apothecary/blob/master/apothecary/linuxarmv6l_configure.sh

**Comment by dimitre** [comment]
@ofTheo I've now added other script just replacing the name and architecture.

**Comment by ofTheo** [comment]
@dimitre this is def more tricky than I first thought. 
I don't think the setup in the apothecary runner is fully configured for libxml2 or that version of the lib doesn't recognize the aarch64-linux-gnu toolchain

**Comment by ofTheo** [comment]
closed by #277

**Comment by ofTheo** [comment]
closed by #277

**Pull request closed without merging**
