### PR TITLE
Poco OpenSSL / iOS changes.

### PR DESCRIPTION
**Pull request by danoli3**
Lets try this again shall we

### CODE REVIEW

**Comment by arturoc** [comment]
:) looks great, thanks!

**Comment by danoli3** [comment]
@arturoc Maybe we can split up the travis iOS build for OpenSSL/Poco as well into a new matrix

**Comment by arturoc** [comment]
i think it's failing because it's trying to upload the libraries but it's not finding the key since that can only be run from master. can you pull from master into this branch to see if now it builds properly?

the problem with separating it is that at the end it's uploading all the libraries to the ci server if everything is build together is very easy for people to download the new libraries or the ones for an old version... but if everything is in different tarballs we need some scripts to pull everything...

it's probably slightly slower this way but once everything is setup we won't run this much anyway. for testing you can send a PR that only builds the formulas and platforms you are fixing and then revert to build everything before merging

**Comment by danoli3** [comment]
Omg SourceTree 2.2 is broken as hell, stay on 2.1 till they patch it if you use.

**Comment by danoli3** [comment]
@arturoc 

```
Unencrypting key
iv undefined
 ^ Received error ^
cat: formula.log: No such file or directory
The command "scripts/build.sh $OPT" exited with 1.

```
Seemed to work except that at the end 

iOS Still timing out, not much I can do on that, Poco compile takes 40 minutes alone. I had to write those scripts up for apothecary-den travis to survive the 10 minute compile times.

**Comment by arturoc** [comment]
huh, that's strange it shouldn't be arriving at that line if the branch is not master, i've added quotes to the check just in case but it should be working.

i was having that same problem for osx and saved some time by not compiling several times but instead passing all the architectures to build to clang, not sure if that will be enough for ios. 

if that doesn't work then we can perhaps build each arch for ios in a different matrix or each library? and then have scripts that join everything but it would be so much easier if we could make it work in only one

**Comment by danoli3** [comment]
Oh master is always going to be true, as it is merging to master... I'll fix with this...
```
if [[ $TRAVIS_PULL_REQUEST == "false"
```

**Comment by danoli3** [comment]
Not sure whats happening with the zips but the vars travis command is working now.

**Comment by arturoc** [comment]
i think the problem is that curl doesn't manage redirects very well, i've changed it to use wget instead. can you pull from master again to see if that fixes it?

**Comment by danoli3** [comment]
Looking good! Now just

```
/home/travis/build/openframeworks/apothecary/apothecary/build/poco/Foundation/obj/Linux/x86_64/debug_static64/ArchiveStrategy.o
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-m64’
make[1]: *** [/home/travis/build/openframeworks/apothecary/apothecary/build/poco/Foundation/obj/Linux/x86_64/debug_static64/ArchiveStrategy.o] Error 1
make[1]: Leaving directory `/home/travis/build/openframeworks/apothecary/apothecary/build/poco/Foundation'
make: *** [Foundation-libexec] Error 2
```

In linux

And the iOS Timeout.

Should we merge and I'll look into splitting / optimising poco

**Comment by arturoc** [comment]
that m64 is not happening in master, it might be some leak from other platforms or some setting that has been moved out of ios or something like that?

**Comment by danoli3** [comment]
The -m64 tag exists on master, however doesn't function on Poco 1.6.1 it seems... confused.

**Comment by danoli3** [comment]
Yeah so max time is 50 minutes in total for all travis-ci builds.

Poco I have scaled to take currently: Elapsed time 30 min 52 sec. I'll see if I can use the ARCH enhancement see if that cuts it down by half...

**Comment by danoli3** [comment]
Damn it clang for iOS not liking that... ```target `-arch' given more than once in the same rule.```

**Comment by arturoc** [comment]
mmh ok, what i did for android is just separate the 2 architectures in different elements in the matrix, the problem is that here we need to use lipo later but we could do so with a script when downloading the libraries.

**Comment by arturoc** [comment]
we still need to add assimp and opencv so even if we managed to reduced the compile time for poco i doubt it would be enough anyway.

the linux armv6 thing seems to be fixed now no? in that case i'll merge this and we can look at separating the different archs for ios in a different PR

**Comment by danoli3** [comment]
Good to merge however the fix for the 1.6.1 poco was to step poco to latest SHA. I'm hoping they do release 1.7 soon so it feels more safe. I tested everything, everything seems great. @bakercp any word on a poco release?

**Comment by arturoc** [comment]
but we need this version of poco to work with tvos right?

**Comment by danoli3** [comment]
Yeah need from at least early December Poco

**Comment by arturoc** [comment]
ok, going to merge it then and we can tackle ios later

**Pull request merged**
