### PR TITLE
Libusb build for VS for ofxKinect. Includes needed patch. WIP. 

### PR DESCRIPTION
**Pull request by ofTheo**
Need to add OS-X in. But this works well for Visual Studio. 

Would be great if someone could test with the automated build system to make sure the VS commands work in that environment. 

Also not really sure how the libusb include and libs makes its way to the ofxKinect/libs folder, but I did everything the same as how OpenCV is located - so I am assuming that this is the right way :)

### CODE REVIEW

**Comment by arturoc** [comment]
I think you should have got a mail by now but the automated tests are run every time you send a PR or do a new commit. it seems this is failing in windows cause git needs the credentials there. it looks like clone is working but then some other git command triggers that, perhaps you can just clone directly from the second repo or something like that instead?

**Comment by arturoc** [comment]
btw, if you create the branch in you own repo it won't trigger the tests twice as it's happening now and you won't need to wait for so long. also for testing you can disable which formulas get built by changing:

https://github.com/openframeworks/apothecary/blob/master/scripts/build.sh#L90

with something like:

```
for formula in libusb
```

that way it'll only try to build that formula and you don't need to wait until it builds everything else to see if it worked or not

**Comment by ofTheo** [comment]
@arturoc - thanks for debugging that! 

I just pushed up support for OS X building libusb, which pulls from my libusb repo as I had to change the Xcode project to build static, so I can do the same thing for VS, just host the cherry picked patch there and reduce it to a single clone. 

Will also do the next commits and PR from my apothecary repo - once I pull this stuff in. 

Cheers,
Theo

**Comment by ofTheo** [comment]
Not really sure why there is one failed build for OS X with travis. 
The log doesn't seem to show an error. 

On the VS side it looks like the x86 platforms are failing - it might be related to a Platform Env variable being set.  I think I can fix this.

**Pull request closed without merging**
