### PR TITLE
openFrameworks Cmake Dependancy Upgrades - Android NDK 24 / Android ARM64 / X86_64 / iOS / VS ARM64 / VS 2022 

### PR DESCRIPTION
**Pull request by danoli3**
Android NDK 24  Requirement for Android Studio 4.2+ and new Build Systems

Updated most build scripts

Android Features:

C++17 support
x86_64 Android Target
NDK 23b - Allows for builds with Gradle Systems / Android.mk / CMake In Android Studio
Update to Dependency Libraries
Fixed a bunch of Android configure scripts for NDK 23 + and CMake option / make
Apothecary Changes:

Fixed some documentation

Added to some scripts SHA hash security to check if source zip has been modified / mostly build security for OpenSSL and Curl where these are highly important for clients auditing openFrameworks for security status

Updated **Assimp** from 4.0.1 to **5.2.9** - (Updated Cmake build system)  
Updated **uriparser** from 0.8.5 to **0.9.7** - (New Cmake build system)  
Updated **pugixml** from 1.9 to **1.11.4** - (New Cmake build system)  
Updated **OpenSSL** from 1.1.0h to **1.1.1u** (New Cmake build system, +security patches)  
Updated **cURL** from 7.59.0 to **8.2.0** (New Cmake build system - fixed a bunch most platforms +security patches)  
Updated **OpenCV** from 4.0.1 to 4.7.0 - (New CMake build system and fixed commands, emscripten, android, vs)  
Updated **tess2** - 1.0.2 - (New Cmake build system)  
Updated **FreeImage** (2) from 3.17.0 to 3.19.0 (iOS/tvOS/Android - New CMake Build system - Custom Patched core - These patches are already being used in Unix Fedora core)  
Updated **libxml2** from 2.9.4 to 2.11.4 - (New Cmake build system)  
Updated **FreeType** from 2.7 to **2.13.1** - (New Cmake build system)  
Updated **uri** - (removed Boost from Android make, switched to CMake for Android)  
Updated **Cairo** from 1.14.12 to 1.17.8 - (New Cmake build system)  
Updated **pixman** from 0.34.0 to 0.40.0 - (New Cmake build system)  
Updated **pkg-config.sh** from 0.28 to 0.29.2  
Updated **json** from 3.6.1 to **3.11.2**  
Updated **videoInput** with - (New Cmake build system - patched core)  
Updated **GLFW** 3.3.7 to **3.3.8** - (Updated Cmake build system)  
Updated **GLEW** 1.11.0 to **2.2.0** - (Updated Cmake build system)  
Updated **LibUSB** 1.0.26 to master - (New Cmake build system)  
Updated **GLM** to latest master  
Updated **zlib** to 1.2.13 - - (New Cmake build system)  
Updated **rtAudio** to 6.0.0 - - (New Cmake build system)  
Updated **libPNG** to 1.64.0 - - (New Cmake build system)
Other Notes:

Fixed Android Install for NDK 23 and new download links
FreeImage source code Updated to 3.18.0 for Android and patched for C++17
Removed FreeImage SubComponents (OpenEXR / LibRAWlite) removed from FreeImage util they update to support new compile targets. Updated github.com/danoli3/FreeImage to support C++17 and had to remove these broken libraries for now.
Fixed iOS Configure targets for tvOS / bitcode
Updated Docker to use CMake 3.22.1
Fixed linuxarmv7l/install.sh for new URL
Fixed other scripts in the process:

Updated pixman from 0.34.0 to 0.40.0
Updated pkg-config.sh from 0.28 to 0.29.2
Updated Cairo from 1.14.12 to 1.17.4
Current Issues:

### CODE REVIEW

**Comment by danoli3** [comment]
Updated of https://github.com/openframeworks/apothecary/pull/201 - Will Continue progress here

**Comment by danoli3** [comment]
VSARM64 To fix - OpenCV 
```
Building "opencv"
[53](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:54)

[54](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:55)
Logging to /d/a/apothecary/apothecary/apothecary/build/opencv/build/vs//opencv2-4.5.5.log
[55](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:56)
Looking in links: c:/Users/RUNNER~1/AppData/Local/Temp/tmp24hmameq
[56](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:57)
Processing c:/users/runneradmin/appdata/local/temp/tmp24hmameq/setuptools-63.2.0-py3-none-any.whl
[57](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:58)
Processing c:/users/runneradmin/appdata/local/temp/tmp24hmameq/pip-22.2.1-py3-none-any.whl
[58](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:59)
Installing collected packages: setuptools, pip
[59](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:60)
Successfully installed pip-22.2.1 setuptools-63.2.0
[60](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:61)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[61](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:62)
                                 Dload  Upload   Total   Spent    Left  Speed
[62](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:63)

[63](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:64)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[64](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:65)
100 2500k  100 2500k    0     0   9.7M      0 --:--:-- --:--:-- --:--:--  9.8M
[65](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:66)
Collecting pip
[66](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:67)
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
[67](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:68)
     ---------------------------------------- 2.0/2.0 MB 18.5 MB/s eta 0:00:00
[68](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:69)
Collecting wheel
[69](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:70)
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
[70](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:71)
Installing collected packages: wheel, pip
[71](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:72)
  Attempting uninstall: pip
[72](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:73)
    Found existing installation: pip 22.2.1
[73](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:74)
    Uninstalling pip-22.2.1:
[74](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:75)
      Successfully uninstalled pip-22.2.1
[75](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:76)
Successfully installed pip-22.2.2 wheel-0.37.1
[76](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:77)

[77](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:78)
Usage:   
[78](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:79)
  D:/a/_temp/msys64/mingw64/bin/python3.exe -m pip <command> [options]
[79](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:80)

[80](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:81)
Commands:
[81](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:82)
  install                     Install packages.
[82](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:83)
  download                    Download packages.
[83](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:84)
  uninstall                   Uninstall packages.
[84](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:85)
  freeze                      Output installed packages in requirements format.
[85](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:86)
  inspect                     Inspect the python environment.
[86](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:87)
  list                        List installed packages.
[87](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:88)
  show                        Show information about installed packages.
[88](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:89)
  check                       Verify installed packages have compatible dependencies.
[89](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:90)
  config                      Manage local and global configuration.
[90](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:91)
  search                      Search PyPI for packages.
[91](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:92)
  cache                       Inspect and manage pip's wheel cache.
[92](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:93)
  index                       Inspect information available from package indexes.
[93](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:94)
  wheel                       Build wheels from your requirements.
[94](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:95)
  hash                        Compute hashes of package archives.
[95](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:96)
  completion                  A helper command used for command completion.
[96](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:97)
  debug                       Show information useful for debugging.
[97](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:98)
  help                        Show help for commands.
[98](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:99)

[99](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:100)
General Options:
[100](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:101)
  -h, --help                  Show help.
[101](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:102)
  --debug                     Let unhandled exceptions propagate outside the
[102](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:103)
                              main subroutine, instead of logging them to
[103](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:104)
                              stderr.
[104](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:105)
  --isolated                  Run pip in an isolated mode, ignoring
[105](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:106)
                              environment variables and user configuration.
[106](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:107)
  --require-virtualenv        Allow pip to only run in a virtual environment;
[107](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:108)
                              exit with an error otherwise.
[108](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:109)
  -v, --verbose               Give more output. Option is additive, and can be
[109](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:110)
                              used up to 3 times.
[110](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:111)
  -V, --version               Show version and exit.
[111](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:112)
  -q, --quiet                 Give less output. Option is additive, and can be
[112](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:113)
                              used up to 3 times (corresponding to WARNING,
[113](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:114)
                              ERROR, and CRITICAL logging levels).
[114](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:115)
  --log <path>                Path to a verbose appending log.
[115](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:116)
  --no-input                  Disable prompting for input.
[116](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:117)
  --proxy <proxy>             Specify a proxy in the form
[117](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:118)
                              scheme://[user:passwd@]proxy.server:port.
[118](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:119)
  --retries <retries>         Maximum number of retries each connection should
[119](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:120)
                              attempt (default 5 times).
[120](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:121)
  --timeout <sec>             Set the socket timeout (default 15 seconds).
[121](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:122)
  --exists-action <action>    Default action when a path already exists:
[122](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:123)
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
[123](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:124)
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
[124](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:125)
                              even though it does not have valid or any HTTPS.
[125](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:126)
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
[126](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:127)
                              provided, overrides the default. See 'SSL
[127](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:128)
                              Certificate Verification' in pip documentation
[128](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:129)
                              for more information.
[129](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:130)
  --client-cert <path>        Path to SSL client certificate, a single file
[130](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:131)
                              containing the private key and the certificate
[131](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:132)
                              in PEM format.
[132](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:133)
  --cache-dir <dir>           Store the cache data in <dir>.
[133](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:134)
  --no-cache-dir              Disable the cache.
[134](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:135)
  --disable-pip-version-check
[135](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:136)
                              Don't periodically check PyPI to determine
[136](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:137)
                              whether a new version of pip is available for
[137](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:138)
                              download. Implied with --no-index.
[138](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:139)
  --no-color                  Suppress colored output.
[139](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:140)
  --no-python-version-warning
[140](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:141)
                              Silence deprecation warnings for upcoming
[141](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:142)
                              unsupported Pythons.
[142](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:143)
  --use-feature <feature>     Enable new functionality, that may be backward
[143](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:144)
                              incompatible.
[144](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:145)
  --use-deprecated <feature>  Enable deprecated functionality, that will be
[145](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:146)
                              removed in the future.
[146](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:147)
Requirement already satisfied: pip in d:/a/_temp/msys64/mingw64/lib/python3.10/site-packages (22.2.2)
[147](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:148)
Collecting numpy
[148](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:149)
  Downloading numpy-1.23.2.tar.gz (10.7 MB)
[149](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:150)
     --------------------------------------- 10.7/10.7 MB 59.5 MB/s eta 0:00:00
[150](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:151)
  Installing build dependencies: started
[151](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:152)
  Installing build dependencies: finished with status 'done'
[152](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:153)
  Getting requirements to build wheel: started
[153](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:154)
  Getting requirements to build wheel: finished with status 'error'
[154](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:155)
  error: subprocess-exited-with-error
[155](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:156)
  
[156](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:157)
  Getting requirements to build wheel did not run successfully.
[157](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:158)
  exit code: 1
[158](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:159)
  
[159](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:160)
  [40 lines of output]
[160](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:161)
  Traceback (most recent call last):
[161](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:162)
    File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
[162](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:163)
      main()
[163](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:164)
    File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
[164](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:165)
      json_out['return_val'] = hook(**hook_input['kwargs'])
[165](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:166)
    File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 124, in get_requires_for_build_wheel
[166](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:167)
      backend = _build_backend()
[167](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:168)
    File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 89, in _build_backend
[168](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:169)
      obj = import_module(mod_path)
[169](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:170)
    File "D:/a/_temp/msys64/mingw64/lib/python3.10/importlib/__init__.py", line 126, in import_module
[170](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:171)
      return _bootstrap._gcd_import(name[level:], package, level)
[171](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:172)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[172](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:173)
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[173](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:174)
    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
[174](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:175)
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[175](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:176)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[176](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:177)
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[177](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:178)
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[178](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:179)
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[179](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:180)
    File "<frozen importlib._bootstrap_external>", line 887, in exec_module
[180](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:181)
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[181](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:182)
    File "C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-bt0qseol/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 242, in <module>
[182](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:183)
      monkey.patch_all()
[183](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:184)
    File "C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-bt0qseol/overlay/lib/python3.10/site-packages/setuptools/monkey.py", line 99, in patch_all
[184](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:185)
      patch_for_msvc_specialized_compiler()
[185](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:186)
    File "C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-bt0qseol/overlay/lib/python3.10/site-packages/setuptools/monkey.py", line 162, in patch_for_msvc_specialized_compiler
[186](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:187)
      patch_func(*msvc9('find_vcvarsall'))
[187](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:188)
    File "C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-bt0qseol/overlay/lib/python3.10/site-packages/setuptools/monkey.py", line 149, in patch_params
[188](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:189)
      mod = import_module(mod_name)
[189](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:190)
    File "D:/a/_temp/msys64/mingw64/lib/python3.10/importlib/__init__.py", line 126, in import_module
[190](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:191)
      return _bootstrap._gcd_import(name[level:], package, level)
[191](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:192)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[192](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:193)
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[193](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:194)
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[194](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:195)
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[195](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:196)
    File "<frozen importlib._bootstrap_external>", line 887, in exec_module
[196](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:197)
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[197](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:198)
    File "C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-bt0qseol/overlay/lib/python3.10/site-packages/setuptools/_distutils/msvc9compiler.py", line 295, in <module>
[198](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:199)
      raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
[199](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:200)
  distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
[200](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:201)
  [end of output]
[201](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:202)
  
[202](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:203)
  note: This error originates from a subprocess, and is likely not a problem with pip.
[203](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:204)
error: subprocess-exited-with-error
[204](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:205)

[205](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:206)
Getting requirements to build wheel did not run successfully.
[206](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:207)
exit code: 1
[207](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:208)

[208](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:209)
See above for output.
[209](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:210)

[210](https://github.com/openframeworks/apothecary/runs/8061475705?check_suite_focus=true#step:6:211)
note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by danoli3** [comment]
Okay I'll have a look into this

**Comment by ofTheo** [comment]
Amazing! 
Android is building in CI  - woohoo! 🎉

**Comment by danoli3** [comment]
VS2019 (v142) - 64 bit 
VS2022 (v143) - 64 Bit
VS2022 (v143) - ARM64 

Dependencies now CMake compatible

**Comment by danoli3** [comment]
VS Libs for link testing 

2022 (x64/ARM64)
https://libs.danoli3.com/openFrameworksLibs_3AUG23_VS2022_ARM64.zip
https://libs.danoli3.com/openFrameworksLibs_3AUG23_VS2022_64.zip

2019 / (x86/x64)
https://libs.danoli3.com/openFrameworksLibs_3AUG23_VS2019_64.zip
https://libs.danoli3.com/openFrameworksLibs_3AUG23_VS2019_32.zip

**Comment by danoli3** [comment]
Patches for FreeImage CMake for 3.19.0 needed some minor patching linking issues - Cmake fixes applied at Source

**Comment by danoli3** [comment]
All of this is merged in bleeding closing

**Pull request closed without merging**
