### PR TITLE
Android r15

### PR DESCRIPTION
**Pull request by danzeeeman**
new PR for updates to all the things

### CODE REVIEW

**Comment by bakercp** [comment]
Looking good!  Keep up the good work!

**Comment by HalfdanJ** [comment]
We are currently a bit stuck on a VS bug for Cairo. We dont think it has anything to do with our changes, and think its also happening on master, but is due to some environment change. 

https://ci.appveyor.com/project/arturoc/apothecary/build/2.0.571/job/xf9lhqphvjg3kshb

```
link: unknown option -- n
Try 'link --help' for more information.
make[1]: *** [Makefile.win32:16: release/cairo.dll] Error 1
make[1]: Leaving directory '/c/projects/apothecary/apothecary/build/cairo/src'
make: *** [Makefile.win32:12: cairo] Error 2
 ^ Received error ^
```

Any ideas?

**Comment by tgfrerer** [comment]
I believe i found what causes the block when building cairo using the vs scripts - it's a case of `PATH` shadowing: 

The `mingw` environment provides its own version of `link`, which is the gnu linker, under `/usr/bin/link/. Cairo, however, needs to build using the ms build tools, and a call to `link` in cairo's makefile should call the microsoft incremental linker. 

The ms linker `link.exe` is already in the search path (via `vsvarsall.bat` when initialising the CI build environment), but mingw's linker `/usr/bin/link` is declared earlier in `PATH` and called instead.

I'm working on a fix, and figuring out which build paths (32/64,vs2015/vs2017) are all affected...

**Comment by arturoc** [comment]
going to merge this so @tgfrerer can tests his changes on a new PR. thanks so much for looking into this everyone!

**Pull request merged**
