### PR TITLE
Added Passes to iOS

### PR DESCRIPTION
**Pull request by danoli3**
Having multiple passes like this fixes the issue!

Could work to modulate this with string arrays, however lets see how it builds :)

@arturoc You will have to do some tar.gz magic at the end to merge the zips and save them based.
I was thinking like another matrix running on linux that literally gets the zips at 40 minutes in, and merges them. Any other ideas?

### CODE REVIEW

**Comment by arturoc** [comment]
looks good, i think we don't need to merge them in the server, there'll be a script that downloads the final binaries into peoples computer whenever they want to work off of github or in the final downloadable packages when creating the release or nightly builds.

the script can just download and uncompress both tars and that will recreate the final correct libraries structure

**Comment by danoli3** [comment]
@arturoc Sounds like a plan!

I just fixed up some new issues caught by travis. After it returns green good to merge.

**Comment by arturoc** [comment]
:+1:

**Comment by danoli3** [comment]
Bloody hell Poco. So I did some timings, OpenSSL takes 10 minutes on travis and Poco should take 33. 
Cutting it fine! But it should work.

It was adding 5 extra minutes downloading it, so added that to install phase. fingers crossed.

**Comment by danoli3** [comment]
:anger: POCO! Y U TAKE SO LONG!

**Comment by danoli3** [comment]
Okay weird... I just ran the same script, however with Apothecary Directly and it took 38 minutes:

https://travis-ci.org/danoli3/apothecary-den/builds/113367984

This is build iOS OpenSSL and iOS Poco.
What is happening on this branch that is taking an extra 10 + minutes?

**Comment by arturoc** [comment]
it really depends on the load of the servers, we could divide the tasks further and have openssl and poco compile separately. by the way i removed Poco::Data completely when configuring, i think i moved it out of any specific platform so all platforms would build the same modules but be sure to check that it's like that for iOS too. We could remove some other modules if it's necessary or even build some modules in a different task

**Comment by danoli3** [comment]
Yay!!!

**Comment by arturoc** [comment]
great!

**Comment by danoli3** [comment]
I'll fix the tarball thing on master now to add in OPT2, so it will send / store both tar.gz separately.

**Comment by arturoc** [comment]
great, the download scripts are not working yet anyway so we can look into that later if you want

**Comment by danoli3** [comment]
Downloader or Uploader? I just checked the ci.openframeworks.cc/ and it uploaded the files successfully! 
I guess it was failing on master, not sure if that made a difference, but now it is passing on all matrixes/matrices?

**Pull request merged**
