### PR TITLE
Msys2 svgtiny

### PR DESCRIPTION
**Pull request by oxillo**
Update SvgTiny to latest version.
Fix error of duplicate _ALIGNED symbol.
Needed for openframeworks/openframeworks#6605

### CODE REVIEW

**Comment by arturoc** [comment]
is this ready?

**Comment by oxillo** [comment]
Not yet

**Comment by oxillo** [comment]
Ready to merge.
Locale problem in openframeworks/openframeworks#6644 will be handle in ofxSvg.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
