### PR TITLE
Update aging nlohmann::json to current version.

### PR DESCRIPTION
**Pull request by artificiel**
Been bitten by https://github.com/nlohmann/json/pull/2872

### CODE REVIEW

**Comment by ofTheo** [comment]
@artificiel - thanks for this! 
I think the 18.04 runners stopped working so we'll need to do a PR to fix that first. Once that's in ( and pulled to your PR )hopefully the tests will all pass.

**Comment by ofTheo** [comment]
@artificiel just want to mention I almost have the apothecary CI fixed and updated to 22.04- and will merge this after ( once the tests are working ) 

Thanks!!

**Comment by ofTheo** [comment]
@artificiel -  could you pull in the master branch to your PR branch? 
Thanks!

**Comment by artificiel** [comment]
done!

**Pull request merged**
