### PR TITLE
update to use glfw master

### PR DESCRIPTION
**Pull request by ofTheo**
closes #5871

### CODE REVIEW

**Comment by ofTheo** [comment]
see: https://github.com/openframeworks/openFrameworks/issues/5871

**Comment by arturoc** [comment]
can you change it to a specific hash or even better to 3.3? otherwise every time it's build it'll build a different version which could be broken

**Comment by ofTheo** [comment]
Unfortunately there isn't a 3.3 tag yet. But I can make it be the current master hash as it stands today

**Comment by arturoc** [comment]
oh i see then perhaps let's use current master thorugh it's hash or whatever is the hash that fixed this particular issue

**Comment by ofTheo** [comment]
@arturoc - sounds good, thats what I set it to with the last update.

**Comment by kylemcdonald** [comment]
is there an easy way for me to use this update? i tried:

```
$ git clone https://github.com/openframeworks/apothecary.git
$ mv apothecary/apothecary ~/Documents/openFrameworks/scripts/
$ cd ~/Documents/openFrameworks/scripts/apothecary
$ # edit the fomulas/glfw.sh to update the VER to 58cc4b2c5c2c9a245e09451437dd6f5af4d60c84
$  ./apothecary -t osx -j 6 update glfw
```
but i get this error:

```
OF: /Users/kyle/Documents/openFrameworks/scripts/apothecary/../../../
APOTHECARY: /Users/kyle/Documents/openFrameworks/scripts/apothecary
FORMULAS: /Users/kyle/Documents/openFrameworks/scripts/apothecary/formulas
BUILD: /Users/kyle/Documents/openFrameworks/scripts/apothecary/build
LIBS_DIR: /Users/kyle/Documents/openFrameworks/scripts/apothecary/../
ADDONS: /Users/kyle/Documents/openFrameworks/scripts/apothecary/../../../addons
REL_ADDONS_DIR: /Users/kyle/Documents/openFrameworks/scripts/apothecary/../../../addons

 ----- glfw -----

 Downloading "glfw"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0    381      0 --:--:-- --:--:-- --:--:--   394
100  712k    0  712k    0     0   531k      0 --:--:--  0:00:01 --:--:-- 2718k

 Preparing "glfw"


 Building "glfw"

-- The C compiler identification is unknown
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Checking if C linker supports --verbose
-- Detecting C compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /Users/kyle/anaconda/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /Users/kyle/anaconda/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /Users/kyle/anaconda/share/cmake-3.6/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:68 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/kyle/Documents/openFrameworks/scripts/apothecary/build/glfw/build/CMakeFiles/CMakeOutput.log".
See also "/Users/kyle/Documents/openFrameworks/scripts/apothecary/build/glfw/build/CMakeFiles/CMakeError.log".

 ^ Received error ^
```

**Comment by ofTheo** [comment]
Hmm @kylemcdonald I just tried it on my machine and it worked fine. 
I grabbed the whole glfw formula file as there are two fixes in this PR. 

One thing I noticed is that you are one directory off with the apothecary submodule. 
I think the path to the apothecary tool should be `OF/scripts/apothecary/apothecary/`

It might not be important but that is one difference I noticed. 

Here it the output I got on 10.13: 

```
DesignIOLaptop:Github theo$ cd openFrameworks/scripts/apothecary/apothecary/
DesignIOLaptop:apothecary theo$ ls
PROGRESS.md                     android_configure.sh            doc                             ios_configure.sh                linuxarmv7l_configure.sh
README.md                       apothecary                      formulas                        linuxarmv6l_configure.sh        ostype.sh
DesignIOLaptop:apothecary theo$ ./apothecary update glfw
OF: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/../../../
APOTHECARY: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary
FORMULAS: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/formulas
BUILD: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/build
LIBS_DIR: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/../
ADDONS: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/../../../addons
REL_ADDONS_DIR: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/../../../addons
 
 ----- glfw -----
 
 Downloading "glfw"
 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0     60      0 --:--:--  0:00:02 --:--:--    60
100  712k    0  712k    0     0   221k      0 --:--:--  0:00:03 --:--:-- 1421k
 
 Preparing "glfw"
 
 
 Building "glfw"
 
-- The C compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using Cocoa for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/build/glfw/build
Scanning dependencies of target glfw
[  6%] Building C object src/CMakeFiles/glfw.dir/context.c.o
[ 12%] Building C object src/CMakeFiles/glfw.dir/init.c.o
[ 18%] Building C object src/CMakeFiles/glfw.dir/input.c.o
[ 25%] Building C object src/CMakeFiles/glfw.dir/monitor.c.o
[ 31%] Building C object src/CMakeFiles/glfw.dir/vulkan.c.o
[ 37%] Building C object src/CMakeFiles/glfw.dir/window.c.o
[ 43%] Building C object src/CMakeFiles/glfw.dir/cocoa_init.m.o
[ 50%] Building C object src/CMakeFiles/glfw.dir/cocoa_joystick.m.o
[ 56%] Building C object src/CMakeFiles/glfw.dir/cocoa_monitor.m.o
[ 62%] Building C object src/CMakeFiles/glfw.dir/cocoa_window.m.o
[ 68%] Building C object src/CMakeFiles/glfw.dir/cocoa_time.c.o
[ 75%] Building C object src/CMakeFiles/glfw.dir/posix_thread.c.o
[ 81%] Building C object src/CMakeFiles/glfw.dir/nsgl_context.m.o
[ 87%] Building C object src/CMakeFiles/glfw.dir/egl_context.c.o
[ 93%] Building C object src/CMakeFiles/glfw.dir/osmesa_context.c.o
[100%] Linking C static library libglfw3.a
[100%] Built target glfw
 
 Copying "glfw"
 
include/GLFW/glfw3.h -> /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/..//glfw/include/GLFW/glfw3.h
include/GLFW/glfw3native.h -> /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/..//glfw/include/GLFW/glfw3native.h
build/src/libglfw3.a -> /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/..//glfw/lib/osx/glfw3.a
LICENSE.md -> /Users/theo/Documents/CODE/__OPENFRAMEWORKS/Github/openFrameworks/scripts/apothecary/apothecary/..//glfw/license/LICENSE.md
 
 Finished "glfw"
```

**Comment by arturoc** [comment]
@ofTheo this is still failing to compile in the test servers too, the error is not the same but seems both are cmake errors not compilation, could be related with the version of cmake?

**Comment by ofTheo** [comment]
@arturoc I don't see any error with the AppVeyor build relating to this PR. 

For the Travis one it looks like it could be related to an older cmake or older compiler. Looking at the Travis builds it looks like Xcode 8 is building fine, so I am guessing that it might be a compiler issue on the older Xcode 7.3. 

Trying to find where in the Cmakelist.txt the error is coming from:

```
CMake Error at src/CMakeLists.txt:79 (if):
  if given arguments:
    "STREQUAL" "GNU" "OR" "STREQUAL" "Clang"
  Unknown arguments specified
```

@kylemcdonald which macOS / Xcode are you using?

**Comment by arturoc** [comment]
that sounds good. the problem with windows is just that some times poco times out cause it takes more than an hour to compile. usually it passes when retrying so no worries about that one

**Comment by ofTheo** [comment]
hmm - still not working with that change to quotes. will dig in more :(

**Comment by arturoc** [comment]
it seems we are already using the latest cmake cause we are installing it from brew here:

https://github.com/openframeworks/apothecary/blob/master/scripts/osx/install.sh

so not sure what might be going on. perhaps check the install logs or use a trace to see if we are actually using the cmake from brew and which version it is

**Comment by ofTheo** [comment]
@arturoc I just pushed up a fix and tested it with the Travis that was failing.  The code / config in Cmakelists that was erring only on Xcode 7.3 was for Windows only so I just made it not be run for Apple. 

I'll restart all the Travis and AppVeyor to do one last check - there seem to be some openssl errors but those aren't related to this PR. 

But feel free to merge when they have run.

**Comment by arturoc** [comment]
are you sure you pushed it? i don't see any new commits

**Comment by arturoc** [comment]
ah! ok,

**Comment by ofTheo** [comment]
okay - I think this is good to go!  the failing tests seem to be to do with cairo on Windows and openssl on iOS / macOS.  I can take a look at those separately in a diff PR if needed. The only file that changed in this one is glfw.sh

**Pull request merged**
